name: Build Project
permissions:
  contents: read
  pull-requests: write

on:
    pull_request:
        branches:
            - dev

concurrency:
    group: build-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        TAIGA_PATH_R: ${{ secrets.TAIGA_PATH_R }}
        TAIGA_KEY_PASS_R: ${{ secrets.TAIGA_KEY_PASS_R }}
        TAIGA_STORE_PASS_R: ${{ secrets.TAIGA_STORE_PASS_R }}
        TAIGA_ALIAS_R: ${{ secrets.TAIGA_ALIAS_R }}
        ENCODED_STRING_R: ${{ secrets.TAIGA_KEYSTORE_R }}
        TAIGA_PATH_D: ${{ secrets.TAIGA_PATH_D }}
        TAIGA_KEY_PASS_D: ${{ secrets.TAIGA_KEY_PASS_D }}
        TAIGA_STORE_PASS_D: ${{ secrets.TAIGA_STORE_PASS_D }}
        TAIGA_ALIAS_D: ${{ secrets.TAIGA_ALIAS_D }}
        ENCODED_STRING_D: ${{ secrets.TAIGA_KEYSTORE_D }}
        GITHUB_OAUTH_CLIENT_ID: ${{ secrets.GITHUB_OAUTH_CLIENT_ID }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup Android Environment
        uses: ./.github/actions/android-setup-composite-action

      - name: Restore taigamobilenova_debug.jks
        run: echo $ENCODED_STRING_D | base64 -d > ./taigamobilenova_debug.jks

      - name: Assemble gradle fdroid project
        run: ./gradlew :androidApp:assembleFdroidDebug

      - name: Assemble gradle gplay project
        run: ./gradlew :androidApp:assembleGplayDebug -PgplayBuild

      - name: Run JVM tests
        run: ./gradlew jvmTest